# Form implementation generated from reading ui file 'IOTui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_IOT_UI(object):
    def setupUi(self, IOT_UI):
        IOT_UI.setObjectName("IOT_UI")
        IOT_UI.resize(756, 982)
        self.horizontalLayout = QtWidgets.QHBoxLayout(IOT_UI)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.idshow_Lb = QtWidgets.QLabel(parent=IOT_UI)
        self.idshow_Lb.setObjectName("idshow_Lb")
        self.verticalLayout.addWidget(self.idshow_Lb)
        self.IPshow_Lb = QtWidgets.QLabel(parent=IOT_UI)
        self.IPshow_Lb.setObjectName("IPshow_Lb")
        self.verticalLayout.addWidget(self.IPshow_Lb)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.horizontalLayout.addLayout(self.verticalLayout_3)

        self.retranslateUi(IOT_UI)
        QtCore.QMetaObject.connectSlotsByName(IOT_UI)

    def retranslateUi(self, IOT_UI):
        _translate = QtCore.QCoreApplication.translate
        IOT_UI.setWindowTitle(_translate("IOT_UI", "Form"))
        self.idshow_Lb.setText(_translate("IOT_UI", "id"))
        self.IPshow_Lb.setText(_translate("IOT_UI", "ip"))
